files:
  - source: /translationRecorder/app/src/main/res/values/strings.xml
    translation: >-
      /translationRecorder/app/src/main/res/values-%two_letters_code%/%original_file_name%
  - source: /translationRecorder/door43login/src/main/res/values/strings.xml
    translation: >-
      /translationRecorder/door43login/src/main/res/values-%two_letters_code%/strings.xml
